(() => {
  const root=document.body.dataset.root||"../";
  const categoryKey=document.body.dataset.category||new URLSearchParams(location.search).get("category")||"";
  let categories=[],products=[],currentPage=1,activeBrand="all";const PAGE_SIZE=8;
  const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const normalize=(p)=>p?`${root}${p.replace(/^\.?\//,"")}`:"";
  function meta(){return categories.find(c=>c.key===categoryKey)||{key:categoryKey,name:"Danh mục sản phẩm",filter:"Danh mục",glyph:"PPE",visual:"visual-dark"};}
  function card(p,index){const m=categories.find(c=>c.key===p.category)||meta(),img=normalize(p.image),name=esc(p.name||"Sản phẩm bảo hộ"),brand=esc(p.brand||"Đang cập nhật"),desc=esc(p.description||"Liên hệ Minh Hải để được tư vấn.");return `<article class="product-card category-product-card" data-index="${index}" tabindex="0" role="button">${img?`<div class="product-image"><img src="${esc(img)}" alt="${name}" loading="lazy"></div>`:`<div class="product-image"><div class="product-visual ${esc(m.visual||'visual-dark')}"><span>${esc(m.glyph||'PPE')}</span></div></div>`}<div class="product-body"><span class="tag">${esc((m.name||'Bảo hộ lao động').toUpperCase())}</span><h3>${name}</h3><div class="product-brand">Thương hiệu: ${brand}</div><p>${desc}</p><span class="text-link">Xem thông tin →</span></div></article>`;}
  function openProduct(p){let modal=document.getElementById("category-product-modal");if(!modal){document.body.insertAdjacentHTML("beforeend",`<div id="category-product-modal" class="product-modal" aria-hidden="true"><div class="product-modal-panel" role="dialog" aria-modal="true"><button class="product-modal-close" data-close-category-modal aria-label="Đóng">×</button><div class="product-modal-media" data-modal-media></div><div class="product-modal-body"><span class="tag" data-modal-tag></span><h3 data-modal-name></h3><div class="product-brand" data-modal-brand></div><p data-modal-description></p><a class="btn btn-primary btn-wide" href="${root}#lien-he">Liên hệ hỏi mẫu / báo giá</a></div></div></div>`);modal=document.getElementById("category-product-modal");modal.querySelector("[data-close-category-modal]").onclick=closeProduct;modal.onclick=e=>{if(e.target===modal)closeProduct();};}
    const m=categories.find(c=>c.key===p.category)||meta(),img=normalize(p.image);modal.querySelector("[data-modal-media]").innerHTML=img?`<img src="${esc(img)}" alt="${esc(p.name)}">`:`<div class="product-visual ${esc(m.visual||'visual-dark')}"><span>${esc(m.glyph||'PPE')}</span></div>`;modal.querySelector("[data-modal-tag]").textContent=(m.name||"Bảo hộ lao động").toUpperCase();modal.querySelector("[data-modal-name]").textContent=p.name||"Sản phẩm bảo hộ";modal.querySelector("[data-modal-brand]").textContent=`Thương hiệu: ${p.brand||"Đang cập nhật"}`;modal.querySelector("[data-modal-description]").textContent=p.description||"Liên hệ Minh Hải để được tư vấn.";modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";
  }
  function closeProduct(){const m=document.getElementById("category-product-modal");if(m){m.classList.remove("open");m.setAttribute("aria-hidden","true");document.body.style.overflow="";}}
  function renderBrand(){const sel=document.getElementById("category-brand-filter");if(!sel)return;const inCat=products.filter(p=>p.category===categoryKey);const brands=[...new Set(inCat.map(p=>(p.brand||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"vi"));sel.innerHTML='<option value="all">Tất cả thương hiệu</option>'+brands.map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join("");sel.onchange=e=>{activeBrand=e.target.value;currentPage=1;render();};}
  function pagination(total){const nav=document.getElementById("category-product-pagination");if(!nav)return;const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));currentPage=Math.min(currentPage,pages);nav.hidden=pages<=1;nav.querySelector("[data-page-status]").textContent=`Trang ${currentPage}/${pages}`;const nums=nav.querySelector("[data-page-numbers]");nums.innerHTML=Array.from({length:pages},(_,i)=>i+1).map(n=>`<button type="button" class="page-number${n===currentPage?' active':''}" data-page="${n}">${n}</button>`).join("");nums.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{currentPage=Number(b.dataset.page);render(true)});nav.querySelector("[data-page-prev]").disabled=currentPage===1;nav.querySelector("[data-page-next]").disabled=currentPage===pages;nav.querySelector("[data-page-prev]").onclick=()=>{if(currentPage>1){currentPage--;render(true)}};nav.querySelector("[data-page-next]").onclick=()=>{if(currentPage<pages){currentPage++;render(true)}};}
  function render(scroll=false){const grid=document.getElementById("category-product-grid");if(!grid)return;const all=products.map((p,i)=>({p,i})).filter(({p})=>p.category===categoryKey&&(activeBrand==="all"||(p.brand||"")===activeBrand));if(!all.length){grid.className="product-grid empty";grid.innerHTML='<div class="no-results">Danh mục này chưa có sản phẩm. Có thể bổ sung trong trang quản trị.</div>';pagination(0);return;}const start=(currentPage-1)*PAGE_SIZE;grid.className="product-grid";grid.innerHTML=all.slice(start,start+PAGE_SIZE).map(({p,i})=>card(p,i)).join("");grid.querySelectorAll(".product-card").forEach(el=>{const i=Number(el.dataset.index);const open=()=>openProduct(products[i]);el.onclick=open;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}};});pagination(all.length);if(scroll)grid.scrollIntoView({behavior:"smooth",block:"start"});}
  function applyGenericMeta(){if(!document.body.classList.contains("generic-category-page"))return;const m=meta();document.title=`${m.name} Thái Nguyên | Minh Hải`;document.querySelector("[data-category-title]").textContent=m.name;document.querySelectorAll("[data-category-name]").forEach(el=>el.textContent=m.name);document.querySelector("[data-category-description]").textContent=m.description||`Tham khảo các sản phẩm thuộc danh mục ${m.name} tại Minh Hải.`;}
  async function load(){try{const [cr,pr]=await Promise.all([fetch(`${root}data/categories.json`,{cache:"no-store"}),fetch(`${root}data/products.json`,{cache:"no-store"})]);if(!cr.ok||!pr.ok)throw new Error("fetch failed");const cd=await cr.json(),pd=await pr.json();categories=Array.isArray(cd)?cd:(cd.categories||[]);products=Array.isArray(pd)?pd:(pd.products||[]);}catch(e){console.warn(e);categories=[];products=[];}applyGenericMeta();renderBrand();render();}
  document.addEventListener("keydown",e=>{if(e.key==="Escape")closeProduct();});load();
})();
