(() => {
  const root=document.body.dataset.root||"../";
  const categoryKey=document.body.dataset.category||new URLSearchParams(location.search).get("category")||"";
  let categories=[],products=[],currentPage=1,activeBrand="all"; const PAGE_SIZE=8;
  const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const joinRoot=(p="")=>`${root}${String(p).replace(/^\.\//,"")}`;
  const normalize=(p="")=>p?joinRoot(p.replace(/^\.\//,"")):"";
  const slugify=(v="")=>String(v).toLowerCase().replace(/đ/g,"d").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"san-pham";
  function shortHash(value=""){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(36).slice(0,5)}
  const productSlug=p=>(p.slug||"").trim()||`${slugify(p.name)}-${shortHash(`${p.name}|${p.brand}|${p.category}`)}`;
  const productHref=p=>`${joinRoot("san-pham/chi-tiet.html")}?sp=${encodeURIComponent(productSlug(p))}`;
  const meta=()=>categories.find(c=>c.key===categoryKey)||{key:categoryKey,name:"Danh mục sản phẩm",filter:"Danh mục",glyph:"PPE",visual:"visual-dark"};

  function card(p){const m=categories.find(c=>c.key===p.category)||meta(),img=normalize(p.image),name=esc(p.name||"Sản phẩm bảo hộ"),brand=esc(p.brand||"Đang cập nhật"),desc=esc(p.description||"Xem thông tin chi tiết sản phẩm.");return `<a class="product-card category-product-card" href="${esc(productHref(p))}">${img?`<div class="product-image"><img src="${esc(img)}" alt="${name}" loading="lazy"></div>`:`<div class="product-image"><div class="product-visual ${esc(m.visual||'visual-dark')}"><span>${esc(m.glyph||'PPE')}</span></div></div>`}<div class="product-body"><span class="tag">${esc((m.name||'Bảo hộ lao động').toUpperCase())}</span><h3>${name}</h3><div class="product-brand">Thương hiệu: ${brand}</div><p>${desc}</p><span class="text-link">Xem chi tiết sản phẩm →</span></div></a>`;}
  function renderBrand(){const sel=document.getElementById("category-brand-filter");if(!sel)return;const inCat=products.filter(p=>p.category===categoryKey);const brands=[...new Set(inCat.map(p=>(p.brand||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"vi"));sel.innerHTML='<option value="all">Tất cả thương hiệu</option>'+brands.map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join("");sel.onchange=e=>{activeBrand=e.target.value;currentPage=1;render(true);};}
  function pagination(total){const nav=document.getElementById("category-product-pagination");if(!nav)return;const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));currentPage=Math.min(currentPage,pages);nav.hidden=pages<=1;nav.querySelector("[data-page-status]").textContent=`Trang ${currentPage}/${pages}`;const nums=nav.querySelector("[data-page-numbers]");nums.innerHTML=Array.from({length:pages},(_,i)=>i+1).map(n=>`<button type="button" class="page-number${n===currentPage?' active':''}" data-page="${n}">${n}</button>`).join("");nums.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{currentPage=Number(b.dataset.page);render(true)});nav.querySelector("[data-page-prev]").disabled=currentPage===1;nav.querySelector("[data-page-next]").disabled=currentPage===pages;nav.querySelector("[data-page-prev]").onclick=()=>{if(currentPage>1){currentPage--;render(true)}};nav.querySelector("[data-page-next]").onclick=()=>{if(currentPage<pages){currentPage++;render(true)}};}
  function render(scroll=false){const grid=document.getElementById("category-product-grid");if(!grid)return;const all=products.filter(p=>p.category===categoryKey&&(activeBrand==="all"||(p.brand||"")===activeBrand));if(!all.length){grid.className="product-grid empty";grid.innerHTML='<div class="no-results">Danh mục này chưa có sản phẩm. Có thể bổ sung trong trang quản trị.</div>';pagination(0);return;}const start=(currentPage-1)*PAGE_SIZE;grid.className="product-grid";grid.innerHTML=all.slice(start,start+PAGE_SIZE).map(card).join("");pagination(all.length);if(scroll)grid.scrollIntoView({behavior:"smooth",block:"start"});}
  function applyGenericMeta(){if(!document.body.classList.contains("generic-category-page"))return;const m=meta();document.title=`${m.name} Thái Nguyên | Minh Hải`;document.querySelector("[data-category-title]").textContent=m.name;document.querySelectorAll("[data-category-name]").forEach(el=>el.textContent=m.name);document.querySelector("[data-category-description]").textContent=m.description||`Tham khảo các sản phẩm thuộc danh mục ${m.name} tại Minh Hải.`;}
  async function load(){try{const[cr,pr]=await Promise.all([fetch(joinRoot("data/categories.json"),{cache:"no-store"}),fetch(joinRoot("data/products.json"),{cache:"no-store"})]);if(!cr.ok||!pr.ok)throw new Error("fetch failed");const cd=await cr.json(),pd=await pr.json();categories=Array.isArray(cd)?cd:(cd.categories||[]);products=Array.isArray(pd)?pd:(pd.products||[]);}catch(e){console.warn(e);categories=[];products=[];}applyGenericMeta();renderBrand();render();}load();
})();
